# Generated by Django 5.2 on 2025-04-13 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('bando', models.CharField(choices=[('RUSIA', 'Rusia'), ('UCRANIA', 'Ucrania')], default='RUSIA', max_length=10)),
                ('participaciones', models.PositiveIntegerField(default=0)),
                ('kills', models.PositiveIntegerField(default=0)),
                ('muertes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('murio', models.BooleanField(default=False)),
                ('cantidad_kills', models.PositiveIntegerField(default=0)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_detalle', to='inicio.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Kill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arma', models.CharField(max_length=50)),
                ('distancia', models.FloatField()),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills_hechas', to='inicio.jugador')),
                ('victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veces_muerto', to='inicio.jugador')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='inicio.participacion')),
            ],
        ),
    ]
