# Generated by Django 5.2 on 2025-04-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='disparos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jugador',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participacion',
            name='cantidad_disparos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participacion',
            name='cantidad_hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
