# Generated by Django 5.2 on 2025-04-16 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_jugador_disparos_jugador_hits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='teamkills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participacion',
            name='cantidad_teamkills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Teamkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamkills_realizadas', to='inicio.jugador')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamkills', to='inicio.participacion')),
                ('victima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamkills_recibidas', to='inicio.jugador')),
            ],
        ),
    ]
