# Generated by Django 5.2 on 2025-05-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_partida_participacion_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='comodin',
            field=models.BooleanField(default=False),
        ),
    ]
