# Generated by Django 5.2 on 2025-05-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_jugador_comodin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='bando',
        ),
        migrations.AddField(
            model_name='participacion',
            name='bando',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partida',
            name='ganador',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
