# Generated by Django 5.2 on 2025-05-16 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_remove_jugador_bando_participacion_bando_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='comandante_rusia',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='comandante_ucrania',
        ),
        migrations.AddField(
            model_name='partida',
            name='comandante_east',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_comandante_east', to='inicio.jugador'),
        ),
        migrations.AddField(
            model_name='partida',
            name='comandante_west',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_comandante_west', to='inicio.jugador'),
        ),
        migrations.AddField(
            model_name='partida',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
