# Generated by Django 5.2 on 2025-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_remove_partida_comandante_rusia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='playeruid',
            field=models.CharField(max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
